//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobSet
    {
        public int Id { get; set; }
        public string title { get; set; }
        public string company { get; set; }
        public string address { get; set; }
        public string salary { get; set; }
        public string content { get; set; }
        public string desc { get; set; }
        public System.DateTime createTime { get; set; }
    }
}
